blueprint:
  name: Play and Pause Music Tag with Music Assistant (MASS)
  description: Play music tag with e.g. Spotify uri with MASS and pause playback when the NFC tag is removed
  domain: automation
  input:
    reader_id:
      name: ESPHome NFC reader device
      description: This is your NFC reader
      selector:
        device:
          integration: esphome
    player:
      name: Media Player
      description: This is your media player device in MASS for this reader
      selector:
        entity:
          domain: media_player
          integration: music_assistant
    max_volume:
      name: Maximum Volume
      description: Set the maximum volume level
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
    volume_step:
      name: Volume Step
      description: Set the volume step
      default: 0.05
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01

variables:
  reader_id: !input reader_id
  player: !input player
  volume_step: !input volume_step
  max_volume: !input max_volume

trigger:
  - platform: event
    event_type: esphome.nfc_tag
  - platform: event
    event_type: esphome.tag_removed
  - platform: event
    event_type: esphome.music_tag_play_pause
  - platform: event
    event_type: esphome.music_tag_prev_song
  - platform: event
    event_type: esphome.music_tag_next_song
  - platform: event
    event_type: esphome.music_tag_decrease_volume
  - platform: event
    event_type: esphome.music_tag_increase_volume

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == reader_id }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.nfc_tag" }}'
          - condition: template
            value_template: '{{ "https://www.home-assistant.io/tag/" in trigger.event.data.url }}'
        sequence:
          - event: tag_scanned
            event_data:
              tag_id: '{{ trigger.event.data.url.split("/")[-1] }}'
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.nfc_tag" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(player) == "paused" and trigger.event.data.url == states('sensor.last_scanned_tag_uri') }}
                sequence:
                  - service: media_player.media_play
                    target:
                      entity_id: !input player  
            default:
              sequence:
                - service: esphome.tagreader_last_scanned_tag_uri
                  data:
                    value: '{{ trigger.event.data.url }}'
                - service: music_assistant.play_media
                  data:
                    media_id: "{{ trigger.event.data.url }}"
                  target:
                    entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.tag_removed" and states(player) == "playing" }}'
        sequence:
          - action: media_player.media_pause
            target:
              entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag_play_pause" }}'
        sequence:
          - action: media_player.media_play_pause
            target:
              entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag_prev_song" }}'
        sequence:
          - action: media_player.media_previous_track
            target:
              entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag_next_song" }}'
        sequence:
          - action: media_player.media_next_track
            target:
              entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag_increase_volume" }}'
        sequence:
          - service: media_player.volume_set
            data:
              volume_level: >
                {% set new_volume = (state_attr(player, 'volume_level') | default(0)) + volume_step %}
                {{ [new_volume, max_volume] | min }}
            target:
              entity_id: !input player
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag_decrease_volume" }}'
        sequence:
          - service: media_player.volume_set
            data:
              volume_level: >
                {% set new_volume = (state_attr(player, 'volume_level') | default(0)) - volume_step %}
                {{ [new_volume, 0.0] | max }}
            target:
              entity_id: !input player
