blueprint:
  name: Play Spotify Music Tag on a cast device
  description: Play Spotify music tag with Spotify uri on a cast device
  domain: automation
  input:
    reader_id:
      name: ESPHome NFC reader device
      description: This is your NFC reader
      selector:
        device:
          integration: esphome
    player:
      name: Media Player
      description: This is your cast media player for this reader
      selector:
        entity:
          domain: media_player
          integration: cast
    shuffle:
      name: Shuffle
      description: Enable shuffle mode
      default: true
      selector:
        boolean: {}

variables:
    device_id: !input reader_id
    reader: '{{ device_attr(device_id, "name") }}'

trigger:
  - platform: event
    event_type: esphome.music_tag

condition:
  - condition: template
    value_template: '{{ trigger.event.data.reader.lower() == reader.lower() }}'
  - condition: template
    value_template: '{{ trigger.event.data.url.startswith("spotify:") }}'

action:
  - action: spotcast.start
    data:
      entity_id: !input player
      uri: "{{ trigger.event.data.url }}"
      random_song: !input shuffle

mode: queued
max: 10
