blueprint:
  name: Play and Pause Spotify Music Tag on a cast device
  description: Play Spotify music tag with Spotify uri on a cast device and pause playback when the NFC tag is removed
  domain: automation
  input:
    reader_id:
      name: ESPHome NFC reader device
      description: This is your NFC reader
      selector:
        device:
          integration: esphome
    player:
      name: Media Player
      description: This is your cast media player for this reader
      selector:
        entity:
          domain: media_player
          integration: cast
    shuffle:
      name: Shuffle
      description: Enable shuffle mode
      default: true
      selector:
        boolean: {}

variables:
  device_id: !input reader_id

trigger:
  - platform: event
    event_type: esphome.music_tag
  - platform: event
    event_type: esphome.tag_removed

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == device_id }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.music_tag" }}'
          - condition: template
            value_template: '{{ trigger.event.data.source == "spotify" }}'
        sequence:
          - action: spotcast.start
            data:
              entity_id: !input player
              uri: "{{ trigger.event.data.url }}"
              random_song: !input shuffle
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.event_type == "esphome.tag_removed" }}'
        sequence:
          - action: media_player.media_pause
            target:
              entity_id: !input player

mode: queued
max: 10
